// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type QueueEnqueueRequestBody struct {
	Data map[string]any `json:"data"`
	// Delay in seconds before processing
	Delay *int64 `json:"delay,omitempty"`
	Type  string `json:"type"`
}

func (q *QueueEnqueueRequestBody) GetData() map[string]any {
	if q == nil {
		return map[string]any{}
	}
	return q.Data
}

func (q *QueueEnqueueRequestBody) GetDelay() *int64 {
	if q == nil {
		return nil
	}
	return q.Delay
}

func (q *QueueEnqueueRequestBody) GetType() string {
	if q == nil {
		return ""
	}
	return q.Type
}

// QueueEnqueueResponseBody - Job enqueued successfully
type QueueEnqueueResponseBody struct {
	JobID   *string `json:"jobId,omitempty"`
	Success *bool   `json:"success,omitempty"`
}

func (q *QueueEnqueueResponseBody) GetJobID() *string {
	if q == nil {
		return nil
	}
	return q.JobID
}

func (q *QueueEnqueueResponseBody) GetSuccess() *bool {
	if q == nil {
		return nil
	}
	return q.Success
}

type QueueEnqueueResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Job enqueued successfully
	Object *QueueEnqueueResponseBody
}

func (q *QueueEnqueueResponse) GetContentType() string {
	if q == nil {
		return ""
	}
	return q.ContentType
}

func (q *QueueEnqueueResponse) GetStatusCode() int {
	if q == nil {
		return 0
	}
	return q.StatusCode
}

func (q *QueueEnqueueResponse) GetRawResponse() *http.Response {
	if q == nil {
		return nil
	}
	return q.RawResponse
}

func (q *QueueEnqueueResponse) GetObject() *QueueEnqueueResponseBody {
	if q == nil {
		return nil
	}
	return q.Object
}
