"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from aerostack.types import BaseModel
from typing_extensions import TypedDict


class AuthSigninRequestBodyTypedDict(TypedDict):
    email: str
    password: str


class AuthSigninRequestBody(BaseModel):
    email: str

    password: str
