"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from aerostack.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Any, Optional
from typing_extensions import NotRequired, TypedDict


class CacheSetRequestBodyTypedDict(TypedDict):
    key: str
    value: Any
    ttl: NotRequired[int]
    r"""Time to live in seconds"""


class CacheSetRequestBody(BaseModel):
    key: str

    value: Any

    ttl: Optional[int] = None
    r"""Time to live in seconds"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["ttl"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class CacheSetResponseBodyTypedDict(TypedDict):
    r"""Value cached successfully"""

    success: NotRequired[bool]


class CacheSetResponseBody(BaseModel):
    r"""Value cached successfully"""

    success: Optional[bool] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["success"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
