"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from aerostack.errors import SDKBaseError
from aerostack.types import BaseModel
from dataclasses import dataclass, field
from enum import Enum
import httpx
from typing import Any, Dict, Optional


class Code(str, Enum):
    AUTH_INVALID_KEY = "AUTH_INVALID_KEY"
    AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
    DB_QUERY_FAILED = "DB_QUERY_FAILED"
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    INTERNAL_ERROR = "INTERNAL_ERROR"


class ErrorResponseData(BaseModel):
    code: Code
    message: str
    details: Optional[Dict[str, Any]] = None


@dataclass(unsafe_hash=True)
class ErrorResponse(SDKBaseError):
    data: ErrorResponseData = field(hash=False)

    def __init__(
        self,
        data: ErrorResponseData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
