// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"net/http"
)

type Role string

const (
	RoleSystem    Role = "system"
	RoleUser      Role = "user"
	RoleAssistant Role = "assistant"
)

func (e Role) ToPointer() *Role {
	return &e
}
func (e *Role) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "system":
		fallthrough
	case "user":
		fallthrough
	case "assistant":
		*e = Role(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Role: %v", v)
	}
}

type Messages struct {
	Content *string `json:"content,omitempty"`
	Role    *Role   `json:"role,omitempty"`
}

func (m *Messages) GetContent() *string {
	if m == nil {
		return nil
	}
	return m.Content
}

func (m *Messages) GetRole() *Role {
	if m == nil {
		return nil
	}
	return m.Role
}

type AiChatRequestBody struct {
	Messages []Messages `json:"messages"`
	Model    *string    `json:"model,omitempty"`
}

func (a *AiChatRequestBody) GetMessages() []Messages {
	if a == nil {
		return []Messages{}
	}
	return a.Messages
}

func (a *AiChatRequestBody) GetModel() *string {
	if a == nil {
		return nil
	}
	return a.Model
}

// AiChatResponseBody - AI response generated
type AiChatResponseBody struct {
	Response *string `json:"response,omitempty"`
}

func (a *AiChatResponseBody) GetResponse() *string {
	if a == nil {
		return nil
	}
	return a.Response
}

type AiChatResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// AI response generated
	Object *AiChatResponseBody
}

func (a *AiChatResponse) GetContentType() string {
	if a == nil {
		return ""
	}
	return a.ContentType
}

func (a *AiChatResponse) GetStatusCode() int {
	if a == nil {
		return 0
	}
	return a.StatusCode
}

func (a *AiChatResponse) GetRawResponse() *http.Response {
	if a == nil {
		return nil
	}
	return a.RawResponse
}

func (a *AiChatResponse) GetObject() *AiChatResponseBody {
	if a == nil {
		return nil
	}
	return a.Object
}
