// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type CacheGetRequestBody struct {
	Key string `json:"key"`
}

func (c *CacheGetRequestBody) GetKey() string {
	if c == nil {
		return ""
	}
	return c.Key
}

// CacheGetResponseBody - Cache value retrieved
type CacheGetResponseBody struct {
	Exists *bool `json:"exists,omitempty"`
	Value  any   `json:"value,omitempty"`
}

func (c *CacheGetResponseBody) GetExists() *bool {
	if c == nil {
		return nil
	}
	return c.Exists
}

func (c *CacheGetResponseBody) GetValue() any {
	if c == nil {
		return nil
	}
	return c.Value
}

type CacheGetResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Cache value retrieved
	Object *CacheGetResponseBody
}

func (c *CacheGetResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CacheGetResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CacheGetResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CacheGetResponse) GetObject() *CacheGetResponseBody {
	if c == nil {
		return nil
	}
	return c.Object
}
