// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type CacheSetRequestBody struct {
	Key string `json:"key"`
	// Time to live in seconds
	TTL   *int64 `json:"ttl,omitempty"`
	Value any    `json:"value"`
}

func (c *CacheSetRequestBody) GetKey() string {
	if c == nil {
		return ""
	}
	return c.Key
}

func (c *CacheSetRequestBody) GetTTL() *int64 {
	if c == nil {
		return nil
	}
	return c.TTL
}

func (c *CacheSetRequestBody) GetValue() any {
	if c == nil {
		return nil
	}
	return c.Value
}

// CacheSetResponseBody - Value cached successfully
type CacheSetResponseBody struct {
	Success *bool `json:"success,omitempty"`
}

func (c *CacheSetResponseBody) GetSuccess() *bool {
	if c == nil {
		return nil
	}
	return c.Success
}

type CacheSetResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Value cached successfully
	Object *CacheSetResponseBody
}

func (c *CacheSetResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CacheSetResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CacheSetResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CacheSetResponse) GetObject() *CacheSetResponseBody {
	if c == nil {
		return nil
	}
	return c.Object
}
