// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
	"undefined/pkg/models/shared"
)

type DbQueryRequestBody struct {
	// Query parameters for prepared statements
	Params []any `json:"params,omitempty"`
	// SQL query to execute
	SQL string `json:"sql"`
}

func (d *DbQueryRequestBody) GetParams() []any {
	if d == nil {
		return nil
	}
	return d.Params
}

func (d *DbQueryRequestBody) GetSQL() string {
	if d == nil {
		return ""
	}
	return d.SQL
}

type DbQueryResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Query executed successfully
	DbQueryResult *shared.DbQueryResult
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (d *DbQueryResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DbQueryResponse) GetDbQueryResult() *shared.DbQueryResult {
	if d == nil {
		return nil
	}
	return d.DbQueryResult
}

func (d *DbQueryResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DbQueryResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}
