// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type ServicesInvokeRequestBody struct {
	Data        map[string]any `json:"data"`
	ServiceName string         `json:"serviceName"`
}

func (s *ServicesInvokeRequestBody) GetData() map[string]any {
	if s == nil {
		return map[string]any{}
	}
	return s.Data
}

func (s *ServicesInvokeRequestBody) GetServiceName() string {
	if s == nil {
		return ""
	}
	return s.ServiceName
}

// ServicesInvokeResponseBody - Service invoked successfully
type ServicesInvokeResponseBody struct {
	Result  any   `json:"result,omitempty"`
	Success *bool `json:"success,omitempty"`
}

func (s *ServicesInvokeResponseBody) GetResult() any {
	if s == nil {
		return nil
	}
	return s.Result
}

func (s *ServicesInvokeResponseBody) GetSuccess() *bool {
	if s == nil {
		return nil
	}
	return s.Success
}

type ServicesInvokeResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Service invoked successfully
	Object *ServicesInvokeResponseBody
}

func (s *ServicesInvokeResponse) GetContentType() string {
	if s == nil {
		return ""
	}
	return s.ContentType
}

func (s *ServicesInvokeResponse) GetStatusCode() int {
	if s == nil {
		return 0
	}
	return s.StatusCode
}

func (s *ServicesInvokeResponse) GetRawResponse() *http.Response {
	if s == nil {
		return nil
	}
	return s.RawResponse
}

func (s *ServicesInvokeResponse) GetObject() *ServicesInvokeResponseBody {
	if s == nil {
		return nil
	}
	return s.Object
}
