// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type File struct {
	// This field accepts []byte data or io.Reader implementations, such as *os.File.
	Content  any    `multipartForm:"content"`
	FileName string `multipartForm:"name=fileName"`
}

func (f *File) GetContent() any {
	if f == nil {
		return nil
	}
	return f.Content
}

func (f *File) GetFileName() string {
	if f == nil {
		return ""
	}
	return f.FileName
}

type StorageUploadRequestBody struct {
	ContentType *string `multipartForm:"name=contentType"`
	File        File    `multipartForm:"file,name=file"`
	// Storage key/path
	Key string `multipartForm:"name=key"`
}

func (s *StorageUploadRequestBody) GetContentType() *string {
	if s == nil {
		return nil
	}
	return s.ContentType
}

func (s *StorageUploadRequestBody) GetFile() File {
	if s == nil {
		return File{}
	}
	return s.File
}

func (s *StorageUploadRequestBody) GetKey() string {
	if s == nil {
		return ""
	}
	return s.Key
}

// StorageUploadResponseBody - File uploaded successfully
type StorageUploadResponseBody struct {
	URL *string `json:"url,omitempty"`
}

func (s *StorageUploadResponseBody) GetURL() *string {
	if s == nil {
		return nil
	}
	return s.URL
}

type StorageUploadResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// File uploaded successfully
	Object *StorageUploadResponseBody
}

func (s *StorageUploadResponse) GetContentType() string {
	if s == nil {
		return ""
	}
	return s.ContentType
}

func (s *StorageUploadResponse) GetStatusCode() int {
	if s == nil {
		return 0
	}
	return s.StatusCode
}

func (s *StorageUploadResponse) GetRawResponse() *http.Response {
	if s == nil {
		return nil
	}
	return s.RawResponse
}

func (s *StorageUploadResponse) GetObject() *StorageUploadResponseBody {
	if s == nil {
		return nil
	}
	return s.Object
}
