"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .user import User, UserTypedDict
from aerostack.types import BaseModel, UNSET_SENTINEL
from datetime import datetime
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class AuthResponseTypedDict(TypedDict):
    expires_at: NotRequired[datetime]
    token: NotRequired[str]
    r"""JWT authentication token"""
    user: NotRequired[UserTypedDict]


class AuthResponse(BaseModel):
    expires_at: Annotated[Optional[datetime], pydantic.Field(alias="expiresAt")] = None

    token: Optional[str] = None
    r"""JWT authentication token"""

    user: Optional[User] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["expiresAt", "token", "user"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    AuthResponse.model_rebuild()
except NameError:
    pass
