"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from aerostack.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Any, Optional
from typing_extensions import NotRequired, TypedDict


class CacheGetRequestBodyTypedDict(TypedDict):
    key: str


class CacheGetRequestBody(BaseModel):
    key: str


class CacheGetResponseBodyTypedDict(TypedDict):
    r"""Cache value retrieved"""

    exists: NotRequired[bool]
    value: NotRequired[Nullable[Any]]


class CacheGetResponseBody(BaseModel):
    r"""Cache value retrieved"""

    exists: Optional[bool] = None

    value: OptionalNullable[Any] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["exists", "value"])
        nullable_fields = set(["value"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
