"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from aerostack.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Any, Dict, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class QueueEnqueueRequestBodyTypedDict(TypedDict):
    data: Dict[str, Any]
    type: str
    delay: NotRequired[int]
    r"""Delay in seconds before processing"""


class QueueEnqueueRequestBody(BaseModel):
    data: Dict[str, Any]

    type: str

    delay: Optional[int] = None
    r"""Delay in seconds before processing"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["delay"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class QueueEnqueueResponseBodyTypedDict(TypedDict):
    r"""Job enqueued successfully"""

    job_id: NotRequired[str]
    success: NotRequired[bool]


class QueueEnqueueResponseBody(BaseModel):
    r"""Job enqueued successfully"""

    job_id: Annotated[Optional[str], pydantic.Field(alias="jobId")] = None

    success: Optional[bool] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["jobId", "success"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    QueueEnqueueResponseBody.model_rebuild()
except NameError:
    pass
