// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package sdkerrors

import (
	"encoding/json"
	"fmt"
)

type Code string

const (
	CodeAuthInvalidKey         Code = "AUTH_INVALID_KEY"
	CodeAuthInvalidCredentials Code = "AUTH_INVALID_CREDENTIALS"
	CodeDbQueryFailed          Code = "DB_QUERY_FAILED"
	CodeRateLimitExceeded      Code = "RATE_LIMIT_EXCEEDED"
	CodeValidationError        Code = "VALIDATION_ERROR"
	CodeInternalError          Code = "INTERNAL_ERROR"
)

func (e Code) ToPointer() *Code {
	return &e
}
func (e *Code) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "AUTH_INVALID_KEY":
		fallthrough
	case "AUTH_INVALID_CREDENTIALS":
		fallthrough
	case "DB_QUERY_FAILED":
		fallthrough
	case "RATE_LIMIT_EXCEEDED":
		fallthrough
	case "VALIDATION_ERROR":
		fallthrough
	case "INTERNAL_ERROR":
		*e = Code(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Code: %v", v)
	}
}

type ErrorResponse struct {
	Code    Code           `json:"code"`
	Details map[string]any `json:"details,omitempty"`
	Message string         `json:"message"`
}

var _ error = &ErrorResponse{}

func (e *ErrorResponse) Error() string {
	data, _ := json.Marshal(e)
	return string(data)
}
