// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"time"
	"undefined/pkg/utils"
)

type AuthResponse struct {
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
	// JWT authentication token
	Token *string `json:"token,omitempty"`
	User  *User   `json:"user,omitempty"`
}

func (a AuthResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AuthResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AuthResponse) GetExpiresAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.ExpiresAt
}

func (a *AuthResponse) GetToken() *string {
	if a == nil {
		return nil
	}
	return a.Token
}

func (a *AuthResponse) GetUser() *User {
	if a == nil {
		return nil
	}
	return a.User
}
