// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type DbQueryResult struct {
	Count   *int64           `json:"count,omitempty"`
	Results []map[string]any `json:"results,omitempty"`
}

func (d *DbQueryResult) GetCount() *int64 {
	if d == nil {
		return nil
	}
	return d.Count
}

func (d *DbQueryResult) GetResults() []map[string]any {
	if d == nil {
		return nil
	}
	return d.Results
}
