// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"time"
	"undefined/pkg/utils"
)

type User struct {
	CreatedAt *time.Time     `json:"createdAt,omitempty"`
	Email     *string        `json:"email,omitempty"`
	ID        *string        `json:"id,omitempty"`
	Metadata  map[string]any `json:"metadata,omitempty"`
	Name      *string        `json:"name,omitempty"`
}

func (u User) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(u, "", false)
}

func (u *User) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &u, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (u *User) GetCreatedAt() *time.Time {
	if u == nil {
		return nil
	}
	return u.CreatedAt
}

func (u *User) GetEmail() *string {
	if u == nil {
		return nil
	}
	return u.Email
}

func (u *User) GetID() *string {
	if u == nil {
		return nil
	}
	return u.ID
}

func (u *User) GetMetadata() map[string]any {
	if u == nil {
		return nil
	}
	return u.Metadata
}

func (u *User) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}
